### ISSUE TITLE
Please consider upgrading this to latest versions

### ISSUE THREAD

**Issue by abhi18av** [acron0/cudgel#1]
Hi @acron0 ,

I found this project while looking for existing `Cljs` wrappers for `Phaser` and proceeded to clone and try this out. However, there are build failures which might be because of older dependencies.

I'm really looking forward to be able to use `Phaser` from `CLJS` but so far, I haven't been able to make any progress. https://github.com/abhi18av/rum-tavern

 Could you please take a look on my project or upgrade dependencies of `cudgel` itself? I'm still kinda new to the ecosystem.

**Comment by acron0** [comment]
@abhi18av I genuinely appreciate the interest here but this project is so far off my radar at the moment, it's unlikely I will ever come back to it. There's more chance I'd start afresh. Sorry.

**Comment by abhi18av** [comment]
@acron0, I understand. No worries :)
